#!/bin/sh

##############################################################
# SYSTEM SECTION
##############################################################
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

##############################################################
# USER SECTION
##############################################################

# Xprofile
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

# Window Manager
if [[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/dwm/dwmrc" ]]; then
  . "${XDG_CONFIG_HOME:-$HOME/.config}/dwm/dwmrc"
fi
exec /usr/local/bin/dwm
