#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

[ -x "$HOME/.fehbg" ] && "$HOME/.fehbg" # set the background
setxkbmap us altgr-intl                 # keyboard layout
xset r rate 220 38 &	                  # speed up key repeat rate
unclutter &		                          # remove mouse when idle
nm-applet &                             # network manager
volumeicon &                            # simple volume control icon
redshift-qt &                           # adjust color temperature for night
xfce4-power-manager &                   # power manager
/usr/lib/xfce4/notifyd/xfce4-notifyd &  # notification daemon
